---
- name: Create apt keyrings directory # docker 저장소 키 저장 디렉토리 생성
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key # 공식 GPG 키 다운로드
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Install python3-debian # deb822_repository 사용을 위한 패키지 설치
  ansible.builtin.apt:
    name: python3-debian
    state: present
    update_cache: true

- name: Remove legacy Docker apt repository # 기존 docker 저장소 제거
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Add Docker apt repository # 공식 apt 저장소 등록
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - https://download.docker.com/linux/ubuntu
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true

- name: Install Docker packages # docker 패키지 설치
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable and Start Docker service # docker 서비스 실행 및 자동 시작 설정
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add app user to docker group # docker 그룹에 azureuser 추가
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true