"""create user model

Revision ID: 191452b9771b
Revises: 
Create Date: 2026-06-19 16:54:18.257351+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '191452b9771b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='사용자 ID'),
    sa.Column('provider', sa.Enum('KAKAO', 'GOOGLE', 'APPLE', name='oauth_provider'), nullable=False, comment='소셜 로그인 제공자'),
    sa.Column('provider_id', sa.String(length=100), nullable=False, comment='Provider에서 제공된 식별자'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='사용자 이름'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Provider에서 제공된 이메일'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True, comment='성별'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='생년월일'),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), server_default='USER', nullable=False, comment='사용자 권한'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'WITHDRAWN', name='user_account_status'), server_default='ACTIVE', nullable=False, comment='사용자 계정 상태'),
    sa.Column('candidate_place_enabled', sa.Boolean(), server_default='false', nullable=False, comment='딸깍 생성 알림 활성화 여부'),
    sa.Column('vote_deadline_enabled', sa.Boolean(), server_default='false', nullable=False, comment='투표 마감 알림 활성화 여부'),
    sa.Column('schedule_confirmed_enabled', sa.Boolean(), server_default='false', nullable=False, comment='일정 확정 알림 활성화 여부'),
    sa.Column('quiet_recommendation_enabled', sa.Boolean(), server_default='false', nullable=False, comment='일정 생성 권유 알림 활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일자'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일자'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제 일자'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_users_provider_provider_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
