"""add term tables

Revision ID: 7ab4b50eae24
Revises: 4c6f8b2e1a90
Create Date: 2026-07-08 17:20:29.175806+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ab4b50eae24'
down_revision: Union[str, None] = '4c6f8b2e1a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.UUID(), nullable=False, comment='약관 ID'),
    sa.Column('type', sa.Enum('SERVICE', 'PRIVACY', name='term_type'), nullable=False, comment='약관 유형'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='약관 타이틀'),
    sa.Column('version', sa.String(length=10), server_default='v1.0', nullable=False, comment='약관 버전'),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False, comment='필수 동의 여부'),
    sa.Column('content_url', sa.String(length=2048), nullable=False, comment='약관 본문 URL'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='활성 여부'),
    sa.Column('effective_at', sa.Date(), nullable=False, comment='약관 적용 시작일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일자'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일자'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제 일자'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_terms_agreements',
    sa.Column('id', sa.UUID(), nullable=False, comment='약관 동의 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='사용자 ID'),
    sa.Column('term_id', sa.UUID(), nullable=False, comment='약관 ID'),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False, comment='동의 일자'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='철회 일자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일자'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일자'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='삭제 일자'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_terms_agreements_term_id', 'user_terms_agreements', ['term_id'], unique=False)
    op.create_index('ix_user_terms_agreements_user_id', 'user_terms_agreements', ['user_id'], unique=False)
    op.create_index(
        'uq_user_terms_agreements_active_user_term',
        'user_terms_agreements',
        ['user_id', 'term_id'],
        unique=True,
        postgresql_where=sa.text('revoked_at IS NULL AND deleted_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS uq_user_terms_agreements_active_user_term')
    op.drop_index('ix_user_terms_agreements_user_id', table_name='user_terms_agreements')
    op.drop_index('ix_user_terms_agreements_term_id', table_name='user_terms_agreements')
    op.drop_table('user_terms_agreements')
    op.drop_table('terms')
    sa.Enum(name='term_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
