"""add user withdrawal reason table

Revision ID: 9bfc3a3c583a
Revises: 180892208312
Create Date: 2026-06-29 01:22:14.864361+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9bfc3a3c583a'
down_revision: Union[str, None] = 'a2d280afa318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_withdrawal_reasons',
    sa.Column('id', sa.UUID(), nullable=False, comment='탈퇴 사유 ID'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='사용자 ID'),
    sa.Column('reason', sa.Enum('RARELY_USE', 'MISSING_FEATURES', 'DIFFICULT_TO_USE', 'NO_TIME_TO_USE', 'ETC', name='withdrawal_reason'), nullable=False, comment='탈퇴 사유'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reason', name='uq_user_withdrawal_reasons_user_id_reason')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_withdrawal_reasons')
    # ### end Alembic commands ###
