from app.core.exceptions.base import AppException
from app.core.exceptions.common import *
from app.core.exceptions.auth import *
from app.core.exceptions.external import *
from app.core.exceptions.user import *
from app.core.exceptions.recurring_schedule import *
from app.core.exceptions.notification_settings import *
from app.core.exceptions.user_withdrawal import *
from app.core.exceptions.room import *
from app.core.exceptions.image import *
from app.core.exceptions.place import *
from app.core.exceptions.plan import *
from app.core.exceptions.notification import *

__all__ = [
    "AppException",

    # Common Exceptions
    "BadRequestException",
    "ConflictException",
    "ForbiddenException",
    "NotFoundException",
    "UnauthorizedException",
    "InternalServerException",
    "BadGatewayException",
    "ServiceUnavailableException",
    "TermsNotFoundException",
    "TermsLookupFailedException",

    # Auth Exceptions
    "UnsupportedProviderException",
    "AuthorizationCodeMissingException",
    "InvalidAuthorizationCodeException",
    "RequiredUserInfoMissingException",
    "AuthorizationCodeExpiredException",
    "SocialLoginFailedException",
    "TokenMissingException",
    "AuthorizationHeaderMissingException",
    "AccessTokenMissingException",
    "TokenExpiredException",
    "InvalidTokenException",
    "AccessTokenExpiredException",
    "InvalidAccessTokenException",
    "InvalidTokenTypeException",
    "RefreshTokenReusedException",
    "LoggedOutTokenException",
    "BlockedUserException",
    "EmailAlreadyExistsException",
    "TokenIssueFailedException",
    "AppleOAuthConfigurationException",
    "SocialUserInfoFetchFailedException",
    "ExternalAuthServiceUnavailableException",

    # User Exceptions
    "FcmTokenMissingException",
    "FcmTokenBlankException",
    "DeviceTypeMissingException",
    "UnsupportedDeviceTypeException",
    "UserNotFoundException",
    "RequestBodyMissingException",
    "ProfileUpdateFieldsMissingException",
    "InvalidNicknameFormatException",
    "NicknameTooLongException",
    "NicknameContainsInvalidCharacterException",
    "InvalidProfileImageUrlException",
    "ProfileImageUrlNotAllowedException",
    "ProfileUpdateFailedException",
    "TermsAgreementRequestBodyMissingException",
    "TermsAgreementFieldsMissingException",
    "RequiredTermsNotAgreedException",
    "TermsAgreementFailedException",

    # Recurring Schedule Exceptions
    "RecurringScheduleIdInvalidException",
    "RecurringScheduleRequestBodyMissingException",
    "RecurringScheduleUpdateFieldsMissingException",
    "RecurringScheduleActivationMissingException",
    "RecurringScheduleActivationInvalidException",
    "RecurringScheduleTitleMissingException",
    "RecurringScheduleTitleTooLongException",
    "RecurringScheduleDaysMissingException",
    "RecurringScheduleDayInvalidException",
    "RecurringScheduleDaysDuplicatedException",
    "RecurringScheduleStartTimeMissingException",
    "RecurringScheduleEndTimeMissingException",
    "RecurringScheduleTimeInvalidException",
    "RecurringScheduleTimeRangeInvalidException",
    "RecurringScheduleUserNotFoundException",
    "RecurringScheduleNotFoundException",
    "RecurringScheduleListFailedException",
    "RecurringScheduleCreateFailedException",
    "RecurringScheduleUpdateFailedException",
    "RecurringScheduleDeleteFailedException",

    # Notification Settings Exceptions
    "NotificationSettingsRequestBodyMissingException",
    "UnsupportedNotificationSettingException",
    "NotificationSettingsUpdateFieldsMissingException",
    "NotificationSettingValueInvalidException",
    "NotificationSettingsFailedException",

    # User Withdrawal Exceptions
    "UserWithdrawalRequestBodyMissingException",
    "WithdrawalReasonMissingException",
    "UserAlreadyWithdrawnException",
    "UserWithdrawalFailedException",

    # Room Exceptions
    "RoomRequestBodyMissingException",
    "RoomNameMissingException",
    "RoomNameTooLongException",
    "RoomNameInvalidException",
    "RoomColorMissingException",
    "RoomColorInvalidException",
    "RoomIdInvalidException",
    "InviteCodeMissingException",
    "InviteCodeInvalidException",
    "WithdrawnRoomUserException",
    "BlockedRoomUserException",
    "RoomAccessDeniedException",
    "RoomJoinForbiddenException",
    "RoomNotFoundException",
    "InviteCodeRoomNotFoundException",
    "RoomAlreadyJoinedException",
    "RoomCreateFailedException",
    "InviteCodeLookupFailedException",
    "RoomJoinFailedException",
    "RoomUnavailableException",
    "RoomAlreadyLeftException",
    "RoomInfoLookupFailedException",
    "RoomLeaveFailedException",
    "RoomMemberUserIdInvalidException",
    "RoomHostRequiredException",
    "RoomMemberNotFoundException",
    "SelfKickNotAllowedException",
    "HostKickNotAllowedException",
    "RoomMemberAlreadyKickedException",
    "RoomMemberKickFailedException",
    "MyRoomsLookupFailedException",
  
    # Image Exceptions
    "FileMissingException",
    "ImagePurposeMissingException",
    "UnsupportedImagePurposeException",
    "UnsupportedImageFormatException",
    "UnsupportedImageSizeException",
    "ImageUploadFailedException",
    "StorageServerUploadFailedException",
    "StorageServerConnectionFailedException",

    # Place Exceptions
    "PlaceRequestBodyMissingException",
    "PlaceRoomIdMissingException",
    "PlaceRoomIdInvalidException",
    "PlaceIdInvalidException",
    "PlaceTitleMissingException",
    "PlaceTitleTooLongException",
    "PlaceNameTooLongException",
    "PlaceAddressTooLongException",
    "PlaceCoordinateInvalidException",
    "PlaceLinkUrlInvalidException",
    "UnsupportedPlaceLinkUrlException",
    "PlaceImageUrlInvalidException",
    "PlaceUpdateFieldsMissingException",
    "PlacePageValueInvalidException",
    "PlaceKeywordTooLongException",
    "PlaceRoomAccessDeniedException",
    "PlaceModifyAccessDeniedException",
    "PlaceDeleteAccessDeniedException",
    "PlaceRoomNotFoundException",
    "PlaceNotFoundException",
    "PlaceDeletedException",
    "PlaceAlreadyExistsException",
    "PlaceUsedInActivePlanException",
    "PlaceListLookupFailedException",
    "PlaceDetailLookupFailedException",
    "PlaceCreateFailedException",
    "PlaceUpdateFailedException",
    "PlaceDeleteFailedException",
    "PlaceSearchKeywordMissingException",
    "PlaceSearchKeywordTooLongException",
    "UnsupportedPlaceSearchProviderException",
    "PlaceSearchPageRequestInvalidException",
    "PlaceSearchCoordinateInvalidException",
    "PlaceSearchRateLimitExceededException",
    "PlaceSearchFailedException",
    "ExternalPlaceSearchApiFailedException",
    "ExternalPlaceSearchServiceUnavailableException",
    "PlaceImageFileMissingException",
    "PlaceImageFileSizeExceededException",
    "PlaceImageExtractionServiceUnavailableException",
    "PlaceImageExtractionResponseInvalidException",
    "PlaceImageExtractionFailedException",


    # Plan Exceptions
    "PlanRequestBodyMissingException",
    "PlanRoomIdMissingException",
    "PlanRoomIdInvalidException",
    "PlanPlaceIdInvalidException",
    "PlanIdInvalidException",
    "PlanScheduledAtMissingException",
    "PlanScheduledAtInvalidException",
    "PlanResponseDeadlineMissingException",
    "PlanResponseDeadlineInvalidException",
    "PlanScheduledAtPastException",
    "PlanResponseDeadlinePastException",
    "PlanResponseDeadlineAfterScheduleException",
    "PlanStatusFilterInvalidException",
    "PlanPageValueInvalidException",
    "PlanResponseStatusMissingException",
    "PlanTargetUserIdMissingException",
    "PlanTargetUserIdInvalidException",
    "UnsupportedPlanResponseStatusException",
    "PlanRoomAccessDeniedException",
    "PlanCloseAccessDeniedException",
    "PlanResponseAccessDeniedException",
    "PlanRoomNotFoundException",
    "PlanPlaceNotFoundException",
    "PlanNotFoundException",
    "PlanDeletedException",
    "PlanNoDrawablePlaceException",
    "PlanPlaceNotInRoomException",
    "PlanTargetMemberMissingException",
    "PlanAlreadyExistsException",
    "PlanAlreadyClosedException",
    "PlanResponseDeadlinePassedException",
    "PlanPendingMemberNotFoundException",
    "PlanNoAttendingMemberException",
    "PlanDrawFailedException",
    "PlanCreateFailedException",
    "PlanResponsesLookupFailedException",
    "PlanReminderFailedException",
    "PlanCloseFailedException",
    "PlanListLookupFailedException",
    "PlanInvitationLookupFailedException",
    "PlanResponseSaveFailedException",
    "PlanTicketLookupFailedException",
    "PlanTicketNotConfirmedException",

    # Notification Exceptions
    "NotificationIdInvalidException",
    "NotificationPageValueInvalidException",
    "NotificationAccessDeniedException",
    "NotificationResponseAccessDeniedException",
    "NotificationNotFoundException",
    "NotificationDeletedException",
    "NotificationPlanNotFoundException",
    "NotificationNotPlanResponseException",
    "NotificationPlanAlreadyClosedException",
    "NotificationPlanCanceledException",
    "NotificationListLookupFailedException",
    "NotificationVoteScreenLookupFailedException",
    "NotificationReadFailedException",
    "NotificationReadAllFailedException",

    # External Exceptions
    "RedisUnavailableException",
]
